---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes
    when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: install vim text editor
    apt:
      name: vim
    when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: update repository index
    pacman:
      update_cache: yes
    when: ansible_distribution == "Archlinux"

  - name: install vim text editor
    pacman:
      name: vim
    when: ansible_distribution == "Archlinux"
